actions:
    compile_ts:
        - tsc
    lint_ts:
        - tslint -p tsconfig.json -c tslint.json
    copy_libs_ts:
        - cp src/scripts/components/require.js dist/scripts
        - cp src/scripts/types/codemirror/lib/codemirror.js dist/scripts/types/codemirror/lib
        - cp -r src/scripts/types/codemirror/mode dist/scripts/types/codemirror/
    compile_scss:
        - sass src/styles/styles.scss dist/styles/styles.css
    compile_pug:
        - pug src/views/index.pug -o dist
        - pug src/views/components/header.pug -o dist
        - pug src/views/components/footer.pug -o dist
        - pug src/views/home.pug -o dist
        - pug src/views/paste.pug -o dist
        - pug src/views/profile.pug -o dist
    copy_assets:
        - cp -r src/assets dist
        - mv dist/assets/favicon.ico dist
    clean_dist:
        - ${rmdir dist}
        - ${mkdir dist}
        - ${mkdir dist/scripts}
        - ${mkdir dist/scripts/types}
        - ${mkdir dist/scripts/types/codemirror}
        - ${mkdir dist/scripts/types/codemirror/lib}
    template:
        - ${template header.pug header.ts}
        - ${template footer.pug footer.ts}
        - ${template home.pug home.ts}
        - ${template paste.pug paste.ts}
        - ${template profile.pug profile.ts}

configurations:
    - debug

before_build:
    - ${clean_dist}

build_debug:
    - ${compile_pug}
    - ${template}
    - ${compile_ts}
    - ${lint_ts}
    - ${copy_libs_ts}
    - ${compile_scss}
    - ${copy_assets}

watch:
    src/assets:
        - ${copy_assets}
    src/scripts:
        - ${compile_ts}
        - ${lint_ts}
        - ${copy_libs_ts}
    src/styles:
        - ${compile_scss}
    src/views:
        - ${compile_pug}
        - ${template}
        - ${compile_ts}
