language: d

addons:
  mariadb: '10.3'

before_install:
  - mysql -e 'create database if not exists pastemyst;'
  - mysql -e 'create user tester@localhost;'
  - mysql -e 'grant all privileges on pastemyst.* to tester@localhost;'
  - mysql -e 'flush privileges;'

script:
  - dub test --compiler=${DC}
