name: CI

on: [push, pull_request]

jobs:
  build:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dc: [dmd-latest, ldc-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Install D
        uses: mihails-strasuns/setup-dlang@v0.3.1
        with:
          compiler:  ${{ matrix.dc }}
      - name: Build
        run: dub build
      - name: Test
        run: dub test -b unittest-cov
      - name: Coverage report
        if: matrix.os == "ubuntu-latest"
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
