name: CI

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Lint JavaScript
        run: |
          sudo npm install -g jshint
          jshint --exclude-path public/scripts/.jshintignore public/scripts
      - name: Install D
        uses: mihails-strasuns/setup-dlang@v0.3.1
        with:
          compiler: dmd-latest
      - name: Build
        run: dub build
      - name: Style cheks
        run: |
          dub fetch dscanner
          dub run dscanner -- -S source/
      - name: Unit Tests
        run: dub test
